name: A workflow that echos details of a trigger event
on: 
  pull_request:
  issue_comment:
      types: [created]

jobs:
  describe_event:
    name: Describes some event variables
    runs-on: ubuntu-latest
    steps:
      - name: Print details
        run: echo "github.event_name = ${{ github.event_name }} github.ref = ${{ github.ref }} github.sha = ${{ github.sha }} github.event_path = ${{ github.event_path }}"
      - name: Cat event path
        run: cat ${{ github.event_path }}

  try_pr_number:
    runs-on: ubuntu-latest
    steps:
#     Turns out this action is named confusingly... should really be "detect if issue is a comment to PR".  
#     pull_request is only returned true if both issue_comment AND it is on a pr
    - uses: jmatsu/detect-issue-comment-to-pr-action@v1.0
      id: pr_number
    - run: echo "Previous event returned is_pull_request == ${{ steps.pr_number.outputs.is_pull_request }}, pull_number == ${{ steps.pr_number.outputs.pull_number }}"
    - run: echo "I triggered on PR ${{ steps.pr_number.outputs.pull_number }}, or a comment to that PR"
      if: steps.pr_number.outputs.is_pull_request == 'true'
    - run: echo "I'm not a pull request"
      if: steps.pr_number.outputs.is_pull_request != 'true'
    - name: Add info back as a comment on PR
      if: steps.pr_number.outputs.is_pull_request == 'true'
      env:
          URL: ${{ github.event.issue.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     from https://stackoverflow.com/questions/58066966/commenting-a-pull-request-in-a-github-action
      run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "I triggered on PR ${{ steps.pr_number.outputs.pull_number }}, or a comment to that PR" }'
    - name: Test exit status
      if: steps.pr_number.outputs.is_pull_request != 'true'
      run: |
        echo "That's not good"
        exit 1      
