name: A workflow that echos details of a trigger event
on: 
  pull_request:
  issue_comment:
      types: [created]

jobs:
  describe_event:
    name: Describes some event variables
    runs-on: ubuntu-latest
    steps:
      - name: Print details
        run: echo "github.event_name = ${{ github.event_name }} github.ref = ${{ github.ref }} github.sha = ${{ github.sha }}"
