name: A workflow that echos details of a trigger event
on: 
  pull_request:
  issue_comment:
      types: [created]

jobs:
  describe_event:
    name: Describes some event variables
    runs-on: ubuntu-latest
    steps:
      - name: Print details
        run: echo "github.event_name = ${{ github.event_name }} github.ref = ${{ github.ref }} github.sha = ${{ github.sha }} github.event_path = ${{ github.event_path }}"
      - name: Cat event path
        run: cat ${{ github.event_path }}

  try_pr_number:
    runs-on: ubuntu-latest
    steps:
    - uses: jmatsu/detect-issue-comment-to-pr-action@v1.0
      id: pr_number
    - run: echo "I triggered on PR ${{ steps.filter.outputs.pull_number }}, or a comment to that PR"
      if: steps.filter.outputs.is_pull_request == 'true'
    - run: echo "I'm not a pull request"
      if: steps.filter.outputs.is_pull_request != 'true'
    - name: Add info back as a comment on PR
      if: steps.filter.outputs.is_pull_request == 'true'
      env:
          URL: ${{ github.event.issue.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "I triggered on PR ${{ steps.filter.outputs.pull_number }}, or a comment to that PR" }'

      
