name: A workflow that triggers on comments
on: 
  - issue_comment
  - pull_request

jobs:
  describe_event:
    name: Describes some event variables
    runs-on: ubuntu-latest
    steps:
      - name: Print details
        run: echo "github.event_name = {{ github.event_name }}\ngithub.ref = {{ github.ref }}\n
