name: A workflow that triggers on comments
on: 
  - issue_comment
  - pull_request

jobs:
  build:
    name: Hello world comment edition
    runs-on: ubuntu-latest
    steps:
      - name: Print details
      - run: echo "github.event_name = {{ github.event_name }}\ngithub.ref = {{ github.ref }}\n
